FROM peabody124/datajoint-jupyter

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends graphviz libgraphviz-dev pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER $NB_USER

RUN pip install pygraphviz

ADD AodAnalysis.ipynb .
